# module for configuring the simulator
# configuration parameters are loaded and used both when using the simulator via the CLI and via the interface
# all parameters are required, defaults are in comments

# Probabilistic discrete configuration

# Has to be include for compatibility
inter_arrival_mean: 0
flow_dr_mean: 0
flow_dr_stdev: 0
flow_size_shape: 0
# Has to be include for compatibility           

inter_arrival_values: [5, 10]
inter_arrival_weights: [0.5, 0.5]
flow_dr_values: [1, 2, 4, 6]
flow_dr_weights: [0.3, 0.3, 0.3, 0.1]
flow_duration_values: [1, 2]
flow_duration_weights: [0.5, 0.5]

parameter_mode: probabilistic_discrete
run_duration: 100
inter_measurement: 10