# module for configuring the simulator
# configuration parameters are loaded and used both when using the simulator via the CLI and via the interface
# all parameters are required, defaults are in comments

# Probabilistic continuous configuration

inter_arrival_mean: 0.1            # exponential distribution: lambda
flow_dr_mean: 2.0                  # normal distribution: mean/center of distribution
flow_dr_stdev: 3.0                 # normal distribution: standard deviation
flow_size_shape: 1                 # pareto distribution: alpha

parameter_mode: probabilistic_continuous
run_duration: 100
inter_measurement: 10